### ISSUE TITLE
Android support in the near future?

### ISSUE THREAD

**Issue by ghost** [anael-seghezzi/Maratis-4#1]
Will Maratis ever support android ?

**Comment by anael-seghezzi** [comment]
The code is very portable, some people managed to successfully compile Maratis to Android threw SDL. I think Jurgel did some work on that here https://github.com/jurgel/maratis. We'll try to synchronize and propose both GLFW and SDL backends. I'm opened to suggestions as I don't have access to an Android device.

**Comment by ghost** [comment]
Why do you think Maratis needs GLFW when you have SDL?Also I think you should rename MGUI to M2D or something because I think 2D is needed.

**Comment by anael-seghezzi** [comment]
Well GLFW is much smaller than SDL, and it does the job pretty well for desktops while being super simple to use. Saying that I found SDL very good too. So if maintenance is not an issue, keeping both backends is good. MGui is really a "tools" GUI, not so much adapted for games, it's not really a 2d engine either and cannot render fancy graphics.

**Comment by ghost** [comment]
Then are you going to change MGui any time soon? :)

**Comment by anael-seghezzi** [comment]
Why do you want to change MGui ? it does what it's meant to > editor GUI.
MEngine can be used for 2d with an orthographic camera, even physics can be setup for 2d. But we are getting off-topic (Android).
