### ISSUE TITLE
I don't understand how compile.

### ISSUE THREAD

**Issue by Drakaroft** [anael-seghezzi/Maratis-4#12]
I have follow the tutorial but i alwasy get error like "Cmakelist.txt does not exist in C:\user\Drakenroft"
i have did this things.
open git bash paste this :git clone https://github.com/anael-seghezzi/Maratis-Tiny-C-library.git
and once finished the same for this: git clone https://github.com/anael-seghezzi/Maratis-4.git
openend cmd write mkdir build (that create folder in user)
cd Build and copy in paste this string "cmake -G "Visual Studio 11" ../ -DCMAKE_INSTALL_PREFIX=../bin" where is my error?

**Comment by anael-seghezzi** [comment]
you may need to go inside Maratis-4 directory before "mkdir Build" : 
"cd Maratis-4"
"mkdir Build"
etc 
note: "../" indicates cmake where to find the Cmakelist.txt relative to the current directory

**Comment by Drakaroft** [comment]
Error   6022    error C3861: 'min': identifier not found  
Error   6023    error C3861: 'max': identifier not found
Now i was uble to get the .sln file, but when i try to compile i get those error.
(i'm using visual studio 2013 i change the comand from cmake -G "Visual Studio 11" to cmake -G "Visual Studio 12" and for get the .sln this work but now i have that problem...

**Comment by anael-seghezzi** [comment]
What file produce the error ?
(I don't see the error with visual studio 2012)

**Comment by Drakaroft** [comment]
The file are:
ImathMatrixAlgo.cpp
ImfTiledOutputFile.cpp
ImfTiledMisc.cpp
ImgScanLineInputFile.cpp
ImfOutuputFile.cpp
ImfAccesFile.cpp

**Comment by anael-seghezzi** [comment]
A problem in FreeImage it seems.
Can you try to add on these files : `#include <algorithm>`
Tell me if it works.

**Comment by Drakaroft** [comment]
Nope :( But yes the problem is with FreeImage at the end of compilation another error is "error LNK1104: cannot open file '....\3rdparty\freeimage\Debug\freeimage.lib"        "error C2039: 'max' : is not a member of 'std'  c:\users\andrea_f\maratis-4\3rdparty\freeimage\source\openexr\ilmimf\imfoutputfile.cpp"

**Comment by anael-seghezzi** [comment]
It seems a problem with "Visual Studio 2013 preview"
I don't see another option than adding `#include <algorithm>` add it to this also :
- ImfInputFile.cpp
- ImfPxr24Compressor.cpp
- ImfTiledInputFile.cpp
- ImfB44Compressor.cpp
- ImfRgbaFile.cpp
- ImathQuat.h

Maybe other files in OpenEXR if still nothing.

**Comment by Drakaroft** [comment]
Now it works!!! Thanks!!! But i see that the project is in really early state, when it will be a real working game engine with editor like the oldest release? 
PS now i will try to compile the 3.21 for any problem can i ask here? Thanks :D

**Comment by Drakaroft** [comment]
C:\maratis\trunk\dev>scons.py
scons: Reading SConscript files ...
sys.platform: win32
KeyError: 'SHLINKCOM':
  File "C:\maratis\trunk\dev\SConstruct", line 46:
    platformcustom.customizeEnvironment(env)
  File "C:\maratis\trunk\dev\var\scons\platformcustom.py", line 37:
    embedMSVCManifest(env)
  File "C:\maratis\trunk\dev\var\scons\platformcustom.py", line 28:
    env['SHLINKCOM'] = [env['SHLINKCOM'], 'mt.exe -nologo -manifest ${TARGET}.ma
nifest -outputresource:$TARGET;2']
  File "C:\maratis\trunk\dev\scons-local-2.2.0\SCons\Environment.py", line 412:
    return self._dict[key]
I get this from the 3.21 on google code, what can i do? :D

**Comment by Drakaroft** [comment]
I have python 2.7.11 and Scons 2.4.1

**Comment by anael-seghezzi** [comment]
Let's close this issue first. Can you send a pull request with your OpenEXR modification ?

For Maratis 3.\* you can ask in maratis forum : http://forum.maratis3d.com/
Or you can try this fork that compiles with CMake : https://github.com/dahnielson/Maratis

**Comment by anael-seghezzi** [comment]
RealAquilus don't open a pull request by file !
Only 1 pull request please !

**Comment by Drakaroft** [comment]
Sorry i'm new to github, very very sorry :C

**Comment by anael-seghezzi** [comment]
ho man what a mess... let's cancel the pull request

**Comment by anael-seghezzi** [comment]
Could you close them all please. Thanks

**Comment by Drakaroft** [comment]
I have closed theme all, i think. I'm really really sorry, i was only trying to be helpful to the project but i did a distaster. I'm a retard :(

**Comment by anael-seghezzi** [comment]
It happens...
Let's stop it there, I'm closing this issue.

**Comment by ghost** [comment]
Damn, you guys ... lots of notifications ... much wow :)
