### ISSUE TITLE
SDL Linux Build

### ISSUE THREAD

**Issue by jurgel** [anael-seghezzi/Maratis-4#6]
Should I add build-scripts folder and some files to SDL folder?
Because I failed to run CMake and have to copied some files to make it worked.

*edit
Folder and files which are I included:
- build-scripts/
- sdl2.m4
- sdl2.pc.in
- sdl2-config.in
- SDL2.spec.in

**Comment by anael-seghezzi** [comment]
I just copied all the files except the tests to be safe, tell me if it works ?

**Comment by jurgel** [comment]
Yeah, it works. Thanks.
