### ISSUE TITLE
Cant compile under Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [anael-seghezzi/Maratis-4#7]
[ 95%] Building CXX object Sources/Maratis/Editor/CMakeFiles/MaratisEditor.dir/MPreferences.cpp.o
/home/muresan/Maratis-4/Sources/Maratis/Editor/MPreferences.cpp: In function ‘bool readUByteColor(TiXmlElement_, const char_, float_)’:
/home/muresan/Maratis-4/Sources/Maratis/Editor/MPreferences.cpp:54:40: error: too few arguments to function ‘void m_color_sRGB_to_linear(float_, float_, int)’
   m_color_sRGB_to_linear(vector, vector);
                                        ^
In file included from /home/muresan/Maratis-4/Sources/MSDK/MCore/Includes/MCore.h:59:0,
                 from /home/muresan/Maratis-4/Sources/MSDK/MEngine/Includes/MEngine.h:99,
                 from /home/muresan/Maratis-4/Sources/Maratis/Editor/MEditor.h:48,
                 from /home/muresan/Maratis-4/Sources/Maratis/Editor/MPreferences.cpp:28:
/home/muresan/Maratis-4/../Maratis-Tiny-C-library/include/m_color.h:34:12: note: declared here
 M_API void m_color_sRGB_to_linear(float *src, float *dest, int size);
            ^
make[2]: *_\* [Sources/Maratis/Editor/CMakeFiles/MaratisEditor.dir/MPreferences.cpp.o] Error 1
make[1]: **\* [Sources/Maratis/Editor/CMakeFiles/MaratisEditor.dir/all] Error 2
make: **\* [all] Error 2

done

**Comment by anael-seghezzi** [comment]
yes thanks,
my bad.
