### ISSUE TITLE
libMCore.so missing!

### ISSUE THREAD

**Issue by ghost** [anael-seghezzi/Maratis-4#8]
/home/omx/Dev/Maratis-4-build/Sources/Maratis/Editor/MaratisEditor: error while loading shared libraries: libMCore.so: cannot open shared object file: No such file or directory

I get this after building the whole engine.

**Comment by anael-seghezzi** [comment]
Did you try running MaratisEditor from the "bin/" directory ? Where the binaries are installed.

**Comment by ghost** [comment]
I made it to work,thanks! Are there any official IRC channels where we can talk more?

**Comment by anael-seghezzi** [comment]
Ok, good !
I'm not on IRC, but we can exchange by mail (anael (a) maratis3d.com)
or on maratis forum.
