### ISSUE TITLE
Can't build Maratis with the latest version of Maratis-Tiny-C-lib

### ISSUE THREAD

**Issue by ghost** [anael-seghezzi/Maratis-4#9]
[ 84%] Building CXX object Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o
In file included from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/MColor.cpp:31:0:
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MCore.h:57:20: fatal error: m_base.h: No such file or directory
compilation terminated.
Sources/MSDK/MCore/CMakeFiles/MCore.dir/build.make:62: recipe for target 'Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o' failed
make[2]: **\* [Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o] Error 1
CMakeFiles/Makefile2:817: recipe for target 'Sources/MSDK/MCore/CMakeFiles/MCore.dir/all' failed
make[1]: **\* [Sources/MSDK/MCore/CMakeFiles/MCore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

done

When building with ./build_unix.sh

**Comment by ghost** [comment]
If I comment/remove m_base.h I get lots of new errors.

[ 84%] Building CXX object Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o
In file included from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MCore.h:76:0,
                 from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/MColor.cpp:31:
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:240:85: error: ‘M_TYPES’ has not been declared
 xImage(unsigned int level, unsigned int width, unsigned int height, M_TYPES typ
                                                                     ^
In file included from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MCore.h:76:0,
                 from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/MColor.cpp:31:
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:241:114: error: ‘M_TYPES’ has not been declared
  int xoffset, int yoffset, unsigned int width, unsigned int height, M_TYPES typ
                                                                     ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:299:32: error: ‘M_TYPES’ has not been declared
  virtual void setVertexPointer(M_TYPES type, unsigned int components, const voi
                                ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:300:31: error: ‘M_TYPES’ has not been declared
  virtual void setColorPointer(M_TYPES type, unsigned int components, const void
                               ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:301:32: error: ‘M_TYPES’ has not been declared
  virtual void setNormalPointer(M_TYPES type, const void \* pointer) = 0;
                                ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:302:34: error: ‘M_TYPES’ has not been declared
  virtual void setTexCoordPointer(M_TYPES type, unsigned int components, const v
                                  ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:303:55: error: ‘M_TYPES’ has not been declared
  virtual void setAttribPointer(unsigned int location, M_TYPES type, unsigned in
                                                       ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MRenderingContext.h:307:70: error: ‘M_TYPES’ has not been declared
 virtual void drawElement(M_PRIMITIVE_TYPES type, unsigned int size, M_TYPES ind
                                                                     ^
In file included from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MCore.h:78:0,
                 from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/MColor.cpp:31:
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MPhysicsContext.h:105:169: error: ‘M_TYPES’ has not been declared
 t verticesNumber, const void \* indices, unsigned int indicesNumber, M_TYPES ind
                                                                     ^
In file included from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MCore.h:80:0,
                 from /home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/MColor.cpp:31:
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MImage.h:49:14: error: ‘M_TYPES’ has not been declared
  void create(M_TYPES dataType, unsigned int width, unsigned int height, unsigne
              ^
/home/vlad/Documents/Maratis-4/Sources/MSDK/MCore/Sources/../Includes/MImage.h:56:2: error: ‘M_TYPES’ does not name a type
  M_TYPES getDataType(void){ return (M_TYPES)m_raw.type; }
  ^
Sources/MSDK/MCore/CMakeFiles/MCore.dir/build.make:62: recipe for target 'Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o' failed
make[2]: **\* [Sources/MSDK/MCore/CMakeFiles/MCore.dir/Sources/MColor.cpp.o] Error 1
CMakeFiles/Makefile2:817: recipe for target 'Sources/MSDK/MCore/CMakeFiles/MCore.dir/all' failed
make[1]: **\* [Sources/MSDK/MCore/CMakeFiles/MCore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

done

**Comment by anael-seghezzi** [comment]
Thanks,
it should be ok now.

**Comment by ghost** [comment]
@anael-seghezzi how can I enable the new editor?
